/*
 * Capable Health API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems model module.
 * @module model/AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems
 * @version v0.3
 */
export class AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems {
  /**
   * Constructs a new <code>AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems</code>.
   * @alias module:model/AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems} obj Optional instance to populate.
   * @return {module:model/AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems} The populated <code>AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnyOfworkflowsPersonalizationRuleSetRulesTargetsItems();
    }
    return obj;
  }
}
