/*
 * Capable Health API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The IntegrationsstripeStripeIntegration model module.
 * @module model/IntegrationsstripeStripeIntegration
 * @version v0.3
 */
export class IntegrationsstripeStripeIntegration {
  /**
   * Constructs a new <code>IntegrationsstripeStripeIntegration</code>.
   * @alias module:model/IntegrationsstripeStripeIntegration
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>IntegrationsstripeStripeIntegration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IntegrationsstripeStripeIntegration} obj Optional instance to populate.
   * @return {module:model/IntegrationsstripeStripeIntegration} The populated <code>IntegrationsstripeStripeIntegration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IntegrationsstripeStripeIntegration();
      if (data.hasOwnProperty("enabled"))
        obj.enabled = ApiClient.convertToType(data["enabled"], "Boolean");
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
IntegrationsstripeStripeIntegration.prototype.enabled = undefined;
