// Cache keys used for react-query
export enum ReactQueryKeys {
  BARNARD_CONVERSATION = "BARNARD_CONVERSATION",
  BARNARD_CONVERSATIONS = "BARNARD_CONVERSATIONS",
  CONVERSATION_PARTICIPANTS = "CONVERSATION_PARTICIPANTS",
  CONVERSATION_PATIENT_PARTICIPANTS = "CONVERSATION_PATIENT_PARTICIPANTS",
  MESSAGES = "MESSAGES",
  PATIENT = "PATIENT",
  PATIENT_ACTIVE_SUBSCRIPTION = "PATIENT_ACTIVE_SUBSCRIPTION",
  PATIENT_BARNARD_CONVERSATIONS = "PATIENT_BARNARD_CONVERSATIONS",
  PATIENT_PAYMENT_METHOD = "PATIENT_PAYMENT_METHOD",
  PRACTITIONERS = "PRACTITIONERS",
  PRACTITIONERS_AND_TENANT_ADMINS_DATA = "PRACTITIONERS_AND_TENANT_ADMINS_DATA",
  TWILIO_CLIENT = "TWILIO_CLIENT",
  TWILIO_CONVERSATION = "TWILIO_CONVERSATION",
  TWILIO_TOKEN = "TWILIO_TOKEN",
  USERS = "USERS",
}
