export enum API_Type {
  AppointmentType = "AppointmentType",
  Calendar = "Calendar",
  CarePlanTemplate = "CarePlanTemplate",
  Compound = "Compound",
  Conversation = "Conversation",
  Ethnicity = "Ethnicity",
  Encounter = "Encounter",
  GoalTemplate = "GoalTemplate",
  Integrations = "Integrations",
  LabTest = "LabTest",
  Medication = "Medication",
  MedicationOrder = "MedicationOrder",
  Observation = "Observation",
  ObservationType = "ObservationType",
  Organization = "Organization",
  Patient = "Patient",
  PatientMedication = "PatientMedication",
  Practitioner = "Practitioner",
  Product = "Product",
  Questionnaire = "Questionnaire",
  Race = "Race",
  SetupIntent = "SetupIntent",
  Subscription = "Subscription",
  TargetTemplate = "TargetTemplate",
  TaskTemplate = "TaskTemplate",
  TenantAdmin = "TenantAdmin",
}
