name: CI / CD

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install
      - run: yarn run lint-staged
      - run: yarn run format-check

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install
      - run: yarn run test

  test-app-builds:
    name: Code still builds
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install
      - run: CI=false yarn run build
